name: Postman CLI - CICD Exec

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: BODI_WEB collection
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "Postman_Collection/BODI_WEB.json" -e "Postman_Collection/QA.postman_environment.json"  -d "Postman_Collection/DATA/US BODI dataset.csv" -r htmlextra --reporter-htmlextra-export newman_postman/report.html --iteration-count 1
          # Lint your API using Postman CLI
          postman api lint 83cae4ba-0c77-4d37-b0a9-2ba4f4036d38
