name: Postman CLI - CICD Exec

on:
  workflow_dispatch:
    inputs:
      ScriptJson:
        description: ScriptJson
        type: choice
        required: true
        options:
        - BODI_WEB

jobs:
  bodi_order_place_3mth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: BODI_WEB collection
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run 35363578-de4de25c-e6cf-47ac-8371-520f0f1a9104 -e 35363578-3189c2b0-9207-46d0-a17a-aefd220964df   -d "Postman_Collection/DATA/US BODI dataset.csv" --reporter-htmlextra-export newman_postman/report.html --iteration-count 1
          # Lint your API using Postman CLI
          postman api lint 83cae4ba-0c77-4d37-b0a9-2ba4f4036d38
